<a href="https://colab.research.google.com/github/CosmoAndrade/CursoDePython/blob/master/Python_do_B%C3%A1sico_ao_Avan%C3%A7ado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# `Variáveis`

In [ ]:
nome = 'Cosmo'
sobrenome = 'Andrade'
idade = 36
 
print (nome,sobrenome,idade)

Cosmo Andrade 36


# `Números`
 
```- Adição --> + 
- Subtração -->  -
- Divisão --> /
- Multiplicação -->  *
- Divisão Inteira -->  // 
- Resto da Divisão -->  % 
- Exponenciação --> **
```

In [ ]:
x = 10
y = 3

In [ ]:
print (x + y)

13


In [ ]:
print (x - y)

7


In [ ]:
print(x * y)

30


In [ ]:
print (x / y)

3.3333333333333335


In [ ]:
print (x // y)

3


In [ ]:
print (x % y)

1


In [ ]:
print (x ** y)

1000


 # Tipos de Dados
```
str-> String: Caracteres,  Textos

int-> Números inteiros: 5,8, -6

float -> Números reais: 5.8,4.7,-6.7

bool -> Expressão booleana: True ou False 

type( ) -> Mostrar o tipo de Dado

```

In [ ]:
nome = 'Cosmo'
print (nome)
print (type(nome))

Cosmo
<class 'str'>


In [ ]:
idade = 36
print (idade)
print (type(idade))

36
<class 'int'>


In [ ]:
altura = 1.75
print (altura)
print (type(altura))

1.75
<class 'float'>


In [ ]:
casado = True
print (casado)
print(type(casado))

True
<class 'bool'>


#` Casting (conversão de tipos )`

In [ ]:
x = 5
y = '7'
print (x + y)

TypeError: ignored

In [ ]:
y = int (y)
print (x + y)

12


# `Strings`

In [ ]:
aspas_simples = 'Python'
aspas_duplas = "Python"
asplas_triplas = '''
Curso 
De
Python
'''

In [ ]:
print (aspas_simples)

Python


In [ ]:
print (aspas_duplas)

Python


In [ ]:
print (asplas_triplas)


Curso 
De
Python



# `Métodos e Strings`

In [ ]:
print()
#type()
help(print)


Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [ ]:
curso = 'python'

In [ ]:
maiusculo = curso.upper()
print (maiusculo)


PYTHON


In [ ]:
minusculo = curso.lower()
print(minusculo)

python


In [ ]:
curso = 'curso de python'
print(caixa_alta.title())

Curso De Python


In [ ]:
print (curso.capitalize())

Curso de python


In [ ]:
print (curso.replace('python','Java'))

curso de Java


# `Indexação e Fatiamento de Strings`

In [ ]:
curso = 'Curso de Python'
print (curso)

Curso de Python


In [ ]:
# C u r s o   d e   P y  t  h  o  n
# 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14

In [ ]:
print (len(curso))

15


In [ ]:
print(curso[0])

C


In [ ]:
print (curso[9])

P


In [ ]:
print(curso[-1])

n


In [ ]:
print(curso [0:5])

Curso


In [ ]:
print (curso[2:-1])

rso de Pytho


In [ ]:
print (curso.index('P'))

9


# `Formatação de Strings`

In [ ]:
nome =  'Cosmo'
idade = 26
print (nome,idade)

Cosmo 26


In [ ]:
print ('Nome:{} - Idade:{}'.format(nome,idade))

Nome:Cosmo - Idade:26


In [ ]:
print (f'Nome:{nome} - Idade:{idade}')

Nome:Cosmo - Idade:26


# `Listas []`

In [ ]:
lista = [1,2,3,5]

In [ ]:
print (lista)

[1, 2, 3, 5]


In [ ]:
print (type(lista))

<class 'list'>


In [ ]:
print (len(lista))

4


In [ ]:
print (lista[0])

1


In [ ]:
print (lista[0:3])

[1, 2, 3]


In [ ]:
lista [0] = 8
print (lista)

[8, 3, 1, 4, 2]


In [ ]:
lista.append(6)
print(lista)

[8, 3, 1, 4, 2, 6]


In [ ]:
lista.insert(0,7)
print (lista)

[7, 7, 8, 3, 1, 4, 2, 6]


In [ ]:
print (sum(lista))

38


In [ ]:
print (max(lista))

8


In [ ]:
print (min(lista))

1


In [ ]:
print (lista)

[7, 7, 8, 3, 1, 4, 2, 6]


In [ ]:
lista.pop()
print(lista)

[7, 7, 8, 3, 1, 4, 2]


In [ ]:
lista.remove(7)
print(lista)

[7, 8, 3, 1, 4, 2]


In [ ]:
lista = [2,4,1,3,5]
print (lista)

[2, 4, 1, 3, 5]


In [ ]:
lista.sort()
print (lista)

[1, 2, 3, 4, 5]


In [ ]:
lista.reverse()
print (lista)

[5, 3, 1, 4, 2]


# `Tuplas ()`

In [ ]:
tupla = (1,)
print(tupla)

(1,)


In [ ]:
print(type(tupla))

<class 'tuple'>


In [ ]:
tupla = (1,2,3,4,5)
print(tupla)

(1, 2, 3, 4, 5)


In [ ]:
print (len(tupla))

5


In [ ]:
print (tupla[0])

1


In [ ]:
tupla[0] = 6
print (tupla)

TypeError: ignored

# `Dicionário {}`

## `Chave:Valor`











In [ ]:
cores = {'A':'Verde','B':'Vermelho','C':'Azul'}

In [ ]:
print (cores)

{'A': 'Verde', 'B': 'Vermelho', 'C': 'Azul'}


In [ ]:
print (cores['A'])

Verde


In [ ]:
cores['D'] = 'Laranja'
print (cores)

{'A': 'Verde', 'B': 'Vermelho', 'C': 'Azul', 'D': 'Laranja'}


In [ ]:
print (len(cores))

4


In [ ]:
print (cores.keys())

dict_keys(['A', 'B', 'C', 'D'])


In [ ]:
print (cores.values())

dict_values(['Verde', 'Vermelho', 'Azul', 'Laranja'])


In [ ]:
print (cores.items())

dict_items([('A', 'Verde'), ('B', 'Vermelho'), ('C', 'Azul'), ('D', 'Laranja')])


In [ ]:
print (cores.get('A'))

Verde


In [ ]:
print (cores.pop('D'))
print (cores)

Laranja
{'A': 'Verde', 'B': 'Vermelho', 'C': 'Azul'}


In [ ]:
del cores['C']
print (cores)

{'A': 'Verde', 'B': 'Vermelho'}


# `Operadores de atribuição`

```
+= 	mais igual
-= 	menos igual
*= 	vezes igual
/= 	dividido igual
%= 	módulo igual
```

In [ ]:
x = 5
print (x)

5


In [ ]:
x += 1
print (x)

6


In [ ]:
print (x)

6


In [ ]:
x -=1
print (x)

5


In [ ]:
x *= 2
print (x)

10


# `Operadores de Comparação`

```
> 	maior que
< 	menor que
>= 	maior ou igual a
<= 	menor ou igual a
== 	igual a
!= 	diferente de


```

In [ ]:
x = 7
y = 5
print (x,y)

7 5


In [ ]:
print (x > y)

True


In [ ]:
print (x >= y)

True


In [ ]:
print (x < y)

False


In [ ]:
print (x <= y)

False


In [ ]:
print (x == y)

False


In [ ]:
print (x != y)

True


# `Operadores Lógicos`

```
and - 'e'
or - 'ou'
not - 'não'

```

In [ ]:
x = 7 
y = 5
z = 4

In [ ]:
print (x > 5 and y > z)

True


In [ ]:
print (x > y or x < z)

True


In [ ]:
print (not x > y)

False


In [ ]:
print(not y > x)

True


# `input () - Entrada de dados`

In [ ]:
nome = input('Digite seu nome: ')
idade = int (input('Digite a sua idade: '))
print (f'Seu nome é:{nome}')
print ('A sua idade é:{idade}')

Digite seu nome: Cosmo
Digite a sua idade: 36
Seu nome é:Cosmo
A sua idade é:{idade}


# `Funções`

In [ ]:
# Criação da função com a palavra def ()
def mensagem():
    print ('Olá Tudo Bem !')

In [ ]:
# Chamar a função
mensagem()

Olá Tudo Bem !


In [ ]:
# Função com parâmetro
def mensagem(msg):
    print ('Olá', msg)

In [ ]:
mensagem('Boa Noite!')

Olá Boa Noite!


In [ ]:
# Função com retorno
def soma(x,y):
    return x + y

In [ ]:
print (soma(10,6))

16


# `Condições - if else`

In [ ]:
idade = int (input ('Digite a sua idade: '))

Digite a sua idade: 36


In [ ]:
if idade >= 18:
    print ('Maior de idade!')
else:
    print ('Menor de idade')    

Maior de idade!


In [ ]:
if idade >= 18:
    print ('Maior de idade!')
elif idade < 18:
    print ('Menor de idade!')
else:
    print ('Melhor idade!')        

Maior de idade!


# `Laços (for e while)`

In [ ]:
x = 1

while x < 10:
    print (x)
    x+=1

1
2
3
4
5
6
7
8
9


In [ ]:
for x in range(10):
    print (x)

0
1
2
3
4
5
6
7
8
9


In [ ]:
curso = 'Curso de Python'

In [ ]:
for letra in curso:
    print (letra)

C
u
r
s
o
 
d
e
 
P
y
t
h
o
n


In [ ]:
lista = list(range(10))
print (lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
for item in lista:
    print (item)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for x in range(0,20,2):
    print (x)

0
2
4
6
8
10
12
14
16
18


In [ ]:
import random
aleatorio = random.randint(0,50)
print (aleatorio)

6


In [ ]:
from random import  randint
aleatorio = randint(0,50)
print (aleatorio)

38


In [ ]:

from random import  randint
secreto = randint(0,10)
chute = 0

while  secreto != chute:
    chute = int(input('Digite um número: '))
    if secreto == chute:
         print (f'Você ACERTOU! o número secreto foi: {secreto}')
    else:
       print ('Você ERROU! ')

Digite um número: 1
Você ERROU! 
Digite um número: 2
Você ERROU! 
Digite um número: 3
Você ERROU! 
Digite um número: 4
Você ERROU! 
Digite um número: 5
Você ACERTOU! o número secreto foi: 5


In [ ]:
from random import  randint
senha = randint(0,10)

for leitura in range( senha):
    leitura = int (input ('Digite a senha!'))
    if senha == leitura:
         print ('Acesso liberado!')
         break
    else:
        print ('Senha incorreta , tente novamente')

Digite a senha!7
Senha incorreta , tente novamente
Digite a senha!7
Senha incorreta , tente novamente
Digite a senha!9
Senha incorreta , tente novamente
Digite a senha!8
Acesso liberado!


`break`

In [ ]:
for i in "Python":
        if i == "h":
            break
        print(i)
print(" Fim do loop")

P
y
t
 Fim do loop


`continue`

In [ ]:
for i in "Python":
        if i == "h":
            continue
        print(i)
print("Fim do loop")

P
y
t
o
n
Fim do loop


`enumerate`

In [ ]:
lista = ["p", "y", "t", "h", "o", "n"]

for item in lista:
    print (item)

p
y
t
h
o
n


In [ ]:
for chave, item in enumerate(lista):
    print (chave,item)


0 p
1 y
2 t
3 h
4 o
5 n


# `Erros em Python`

```
try:
    código a tentar
except AlgumaExcecao:
    código a executar no caso da exceção
else:
    código a executar caso não ocorra exceção em try
finally:
    código que é executado sempre, independente de haver uma exceção em andamento ou não

```





In [ ]:
x = 12
y = 0
z = x/y


ZeroDivisionError: ignored

In [ ]:
try:
    z = x/y 
except ZeroDivisionError:
    print('Erro: divisão por zero')

Erro: divisão por zero


In [ ]:
try:
    z = x/y 
except ZeroDivisionError:
    print('Erro: divisão por zero')
finally:
    print ('Fim')    

Erro: divisão por zero
Fim


# `Data em Python`

In [ ]:
from datetime import date

data_atual = date.today()
print(data_atual)

2020-11-25


In [ ]:
data_em_texto = '{}/{}/{}'.format(data_atual.day, data_atual.month,data_atual.year)
print (data_em_texto)

25/11/2020


In [ ]:
data_em_texto = data_atual.strftime('%d/%m/%Y')
print(data_em_texto)

25/11/2020


In [ ]:
from datetime import datetime
data_e_hora_atuais = datetime.now()
data_e_hora_em_texto = data_e_hora_atuais.strftime('%d/%m/%Y')

print(data_e_hora_em_texto)

25/11/2020


# `Manipulando Arquivos`

```
Mode	Explicação
r	Abre o arquivo somente para leitura
r+	Abre o arquivo para leitura e escrita, o ponteiro é colocado no início do arquivo
w	Abre o arquivo somete para escrita, o ponteiro é colocado no início do arquivo, qualquer informação contida no arquivo é removida e se o arquivo não existir, ele é criado
w+	Abre o arquivo para escrita e leitura, o ponteiro é colocado no início do arquivo e qualquer informação contida no arquivo é removida, se o arquivo não existir ele é criado
a	Abre o arquivo somente para escrita, o ponteiro é colocado no final do arquivo, por tanto é possível adicionar informações
a+	Abre o arquivo para escrita e leitura, o ponteiro é colocado no final do arquivo, por tanto é possível adicionar informações

```

In [ ]:
arq = open('lista.txt', 'w')
texto = """
Lista de Alunos
---
João da Silva
José Lima
Maria das Dores
"""
arq.write(texto)
arq.close()

In [ ]:
arq = open('lista.txt', 'w')
texto = """
Lista de Alunos
---
João da Silva
José Lima
Maria das Dores
"""
arq.write(texto)
arq.close()

In [ ]:
arq = open('lista.txt', 'r')
texto = arq.readlines()
for linha in texto :
    print(linha)
arq.close()

Lista de Alunos

---

João da Silva

José Lima

Maria das Dores


In [ ]:
with open('test.txt', 'w') as f:
  f.write("""
Lista de Alunos
---
João da Silva
José Lima
Maria das Dores
""")
  

In [ ]:
with open('test.txt', 'r') as f:  
  print(f.read())


Lista de Alunos
---
João da Silva
José Lima
Maria das Dores



# `Classe em Python`

In [ ]:
class Pessoa:
    pass

pessoa1 = Pessoa()
pessoa1.nome = 'Cosmo'
pessoa1.idade = 36

pessoa2 = Pessoa()
pessoa2.nome = 'Lucas'
pessoa2.idade = 16

In [ ]:
print (pessoa1.nome,pessoa1.idade)
print (pessoa2.nome,pessoa2.idade)

Cosmo 36
Lucas 16


In [ ]:
class Pessoa:
    def __init__(self,nome,idade):
        self.nome = nome
        self.idade = idade

    def imprimir_dados(self):
        return(f'Nome:{self.nome} - Idade: {self.idade}')    



pessoa1 = Pessoa('Cosmo',36)

pessoa2 = Pessoa('Felipe',18)


In [ ]:
print (pessoa1.imprimir_dados())
print (pessoa2.imprimir_dados())

Nome:Cosmo - Idade: 36
Nome:Felipe - Idade: 18


In [ ]:
class Pessoa:
    def __init__(self,nome,idade):
        self.nome = nome
        self.idade = idade

    def __str__(self):
        return(f'Nome:{self.nome} - Idade: {self.idade}')    



pessoa1 = Pessoa('Cosmo',36)

pessoa2 = Pessoa('Felipe',18)


In [ ]:
print (pessoa1)
print (pessoa2)

Nome:Cosmo - Idade: 36
Nome:Felipe - Idade: 18


In [ ]:
class Animal:
    def __init__(self,nome,cor,especie):
        self.nome = nome
        self.cor = cor
        self.especie = especie

    def __str__(self):
        return (f'Nome:{self.nome} - Cor:{self.cor} - Espécie:{self.especie}') 

cao = Animal('Toto','branco','canino')
gato = Animal ('Bilu','preto','felino')               

In [ ]:
print (cao)
print (gato)

Nome:Toto - Cor:branco - Espécie:canino
Nome:Bilu - Cor:preto - Espécie:felino


`Herança em Python`

In [ ]:
class Animal:
    def __init__(self,nome,cor,especie):
        self.nome = nome
        self.cor = cor
        self.especie = especie

    def mensagem(self):
        return(f'{self.nome} - Lindo!')     

class Cachorro(Animal):
    def __init__(self,nome,cor,especie,raca):
        super().__init__(nome,cor,especie)
        self.raca = raca

    def __str__(self):
        return (f'Nome:{self.nome} - Cor:{self.cor} - Espécie:{self.especie} - Raça:{self.raca}')     

    

In [ ]:
animal = Cachorro('Toto','pardo','Canino','Vira-Lata')
print (animal)
print (animal.mensagem())

Nome:Toto - Cor:pardo - Espécie:Canino - Raça:Vira-Lata
Toto - Lindo!


# `Programa jogar Dado`

In [ ]:
import random
print("Este é um siimulador de dados")
x = "y"

while x == "y":
    number = random.randint(1,6)

    if number == 1:
        print("----------")
        print("|        |")
        print("|    O   |")
        print("|        |")
        print("----------")
    if number == 2:
        print("----------")
        print("|        |")
        print("| O    O |")
        print("|        |")
        print("----------")
    if number == 3:
        print("----------")
        print("|    O   |")
        print("|    O   |")
        print("|    O   |")
        print("----------")
    if number == 4:
        print("----------")
        print("| O    O |")
        print("|        |")
        print("| O    O |")
        print("----------")
    if number == 5:
        print("----------")
        print("| O    O |")
        print("|    O   |")
        print("| O    O |")
        print("----------")
    if number == 6:
        print("----------")
        print("| O    O |")
        print("| O    O |")
        print("| O    O |")
        print("----------")
    x = input("Pressione 'y' para rolar novamente: ")
    


Este é um siimulador de dados
----------
|        |
|    O   |
|        |
----------
Pressione 'y' para rolar novamente: y
----------
| O    O |
| O    O |
| O    O |
----------
Pressione 'y' para rolar novamente: x


# `Numpy`

In [ ]:
import numpy as np

In [ ]:
x = [[1,2,3],[4,5,6],[7,8,9]]
print (x)
print (type(x))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [ ]:
y = np.array(x)
print (y)
print (type(y))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [ ]:
print (y[0])

[1 2 3]


In [ ]:
x = [0,1,2,3,4,5,6]
x

[0, 1, 2, 3, 4, 5, 6]

In [ ]:
x = np.array(x)
x

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
z = np.zeros((5))
z

array([0., 0., 0., 0., 0.])

In [ ]:
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0,101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
np.linspace(0,100.5)

array([  0.        ,   2.05102041,   4.10204082,   6.15306122,
         8.20408163,  10.25510204,  12.30612245,  14.35714286,
        16.40816327,  18.45918367,  20.51020408,  22.56122449,
        24.6122449 ,  26.66326531,  28.71428571,  30.76530612,
        32.81632653,  34.86734694,  36.91836735,  38.96938776,
        41.02040816,  43.07142857,  45.12244898,  47.17346939,
        49.2244898 ,  51.2755102 ,  53.32653061,  55.37755102,
        57.42857143,  59.47959184,  61.53061224,  63.58163265,
        65.63265306,  67.68367347,  69.73469388,  71.78571429,
        73.83673469,  75.8877551 ,  77.93877551,  79.98979592,
        82.04081633,  84.09183673,  86.14285714,  88.19387755,
        90.24489796,  92.29591837,  94.34693878,  96.39795918,
        98.44897959, 100.5       ])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
x.max()

6

In [ ]:
x.min()

0

In [ ]:
x = np.array ([ 1, 2, 0, 3, 6, 5 ])
x

array([1, 2, 0, 3, 6, 5])

In [ ]:
x.argmax()

4

In [ ]:
x.argmin()

2

In [ ]:
np.random.rand(10)

array([0.40579896, 0.34591525, 0.44085974, 0.75077934, 0.67502281,
       0.83411312, 0.56978634, 0.45958082, 0.09376355, 0.35160566])

# `Pandas`

In [ ]:
'''Series'''

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x = ['a','b','c','d','e']
y = [1,2,3,4,5]
z = {1:'a',2:'b',3:'c',4:'d',5:'e'}

In [ ]:
pd.Series(x)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [ ]:
serie = pd.Series(data=y,index=x)
serie

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
serie ['a']

1

In [ ]:
serie['a':'b']


a    1
b    2
dtype: int64

In [ ]:
serie2 = pd.Series(data=z)
serie2

1    a
2    b
3    c
4    d
5    e
dtype: object

In [ ]:
'''Dataframes'''

In [ ]:
import pandas as pd


In [ ]:
a = [1,2,3,4]
b = [5,6,7,8]
c = [9,1,3,5]
d = [8,7,4,6]
e = [8,9,10,11]

In [ ]:
df = pd.DataFrame([a,b,c,d,e],['A','B','C','D','E'],['W','X','Y','D'])

In [ ]:
df

W  X   Y   D
A  1  2   3   4
B  5  6   7   8
C  9  1   3   5
D  8  7   4   6
E  8  9  10  11

In [ ]:
dic  = {
    'Alunos': ['Cosmo','Felipe','Lucas'],
    'Faltas': [2,1,1],
    'Prova': [6,8,9],
    'Media': [7,8,9]
}

In [ ]:
df = pd.DataFrame(dic)
df

Alunos  Faltas  Prova  Media
0   Cosmo       2      6      7
1  Felipe       1      8      8
2   Lucas       1      9      9

In [ ]:
df['Alunos']

0     Cosmo
1    Felipe
2     Lucas
Name: Alunos, dtype: object

In [ ]:
df['Media']

0    7
1    8
2    9
Name: Media, dtype: int64

In [ ]:
df.loc[0]

Alunos    Cosmo
Faltas        2
Prova         6
Media         7
Name: 0, dtype: object

In [ ]:
df.loc[1]

Alunos    Felipe
Faltas         1
Prova          8
Media          8
Name: 1, dtype: object

In [ ]:
df.loc[2]

Alunos    Lucas
Faltas        1
Prova         9
Media         9
Name: 2, dtype: object

In [ ]:
df = pd.DataFrame([a,b,c,d,e],['A','B','C','D','E'],['W','X','Y','D'])
df

W  X   Y   D
A  1  2   3   4
B  5  6   7   8
C  9  1   3   5
D  8  7   4   6
E  8  9  10  11

In [ ]:
df['W']

A    1
B    5
C    9
D    8
E    8
Name: W, dtype: int64

In [ ]:
df.loc['A']

W    1
X    2
Y    3
D    4
Name: A, dtype: int64

In [ ]:
df.loc['C','D']

5

In [ ]:
df = pd.DataFrame(dic)
df

Alunos  Faltas  Prova  Media
0   Cosmo       2      6      7
1  Felipe       1      8      8
2   Lucas       1      9      9

In [ ]:
df.loc[2,'Media']

9

In [ ]:
df = pd.DataFrame([a,b,c,d,e],['A','B','C','D','E'],['W','X','Y','D'])
df

W  X   Y   D
A  1  2   3   4
B  5  6   7   8
C  9  1   3   5
D  8  7   4   6
E  8  9  10  11

In [ ]:
df > 3

W      X      Y     D
A  False  False  False  True
B   True   True   True  True
C   True  False  False  True
D   True   True   True  True
E   True   True   True  True

In [ ]:
df [df > 3]

W    X     Y   D
A  NaN  NaN   NaN   4
B  5.0  6.0   7.0   8
C  9.0  NaN   NaN   5
D  8.0  7.0   4.0   6
E  8.0  9.0  10.0  11

In [ ]:
df [df['W']>3]

W  X   Y   D
B  5  6   7   8
C  9  1   3   5
D  8  7   4   6
E  8  9  10  11

In [ ]:
dic = {
    'fruta': ['maça','maça','pera','pera','pera','banana','banana'],
    'dia': ['seg','ter','quar','qui','sex','sab','dom'],
    'valor': [10,20,30,40,50,60,70]
}

In [ ]:
import pandas as pd

df = pd.DataFrame(dic)
df

fruta   dia  valor
0    maça   seg     10
1    maça   ter     20
2    pera  quar     30
3    pera   qui     40
4    pera   sex     50
5  banana   sab     60
6  banana   dom     70

In [ ]:
x = df.groupby('fruta')
x

In [ ]:
x.head()

fruta   dia  valor
0    maça   seg     10
1    maça   ter     20
2    pera  quar     30
3    pera   qui     40
4    pera   sex     50
5  banana   sab     60
6  banana   dom     70

In [ ]:
x.mean()

valor
fruta        
banana     65
maça       15
pera       40

In [ ]:
x.sum()

valor
fruta        
banana    130
maça       30
pera      120

In [ ]:
x.count()

dia  valor
fruta             
banana    2      2
maça      2      2
pera      3      3

In [ ]:
x.max()

dia  valor
fruta             
banana  sab     70
maça    ter     20
pera    sex     50

In [ ]:
x.describe()

valor                                               
       count  mean        std   min   25%   50%   75%   max
fruta                                                      
banana   2.0  65.0   7.071068  60.0  62.5  65.0  67.5  70.0
maça     2.0  15.0   7.071068  10.0  12.5  15.0  17.5  20.0
pera     3.0  40.0  10.000000  30.0  35.0  40.0  45.0  50.0

In [ ]:
import pandas as pd


In [ ]:
filmes = pd.read_csv('dados.csv')
filmes.head()

Nome  Idade Sexo        Tel
0    Cosmo     36    M  8888-7777
1   Felipe     16    M  7777-6666
2    Lucas     14    M  5555-8888
3  Adriana     35    F  4444-9999

In [ ]:
filmes.describe()

Idade
count   4.000000
mean   25.250000
std    11.870833
min    14.000000
25%    15.500000
50%    25.500000
75%    35.250000
max    36.000000

In [ ]:
filmes['Nome']

0      Cosmo
1     Felipe
2      Lucas
3    Adriana
Name: Nome, dtype: object

In [ ]:
filmes['Sexo']

0    M
1    M
2    M
3    F
Name: Sexo, dtype: object

In [ ]:
filmes['Tel']

0    8888-7777
1    7777-6666
2    5555-8888
3    4444-9999
Name: Tel, dtype: object